#!/usr/bin/env python3
# Copyright (c) 2026 Jim Schreckengast
# SPDX-License-Identifier: MIT
"""Generate THIRD-PARTY-LICENSES.md for a release archive.

Runs `cargo bundle-licenses` (https://crates.io/crates/cargo-bundle-licenses)
to harvest the license of every crate compiled into the binary on this
platform, then renders a single readable attribution file:

  * an index of every crate with its version and license expression,
  * every distinct license text found in the crate packages, printed once
    and listing the crates it covers,
  * canonical license texts for crates that declare a license but do not
    package its text.

Crates that are multi-licensed with a copyleft *option* (e.g. "MIT OR
Apache-2.0 OR LGPL-2.1-or-later") are used under a permissive option, and
only that option's text is included.

Usage: python3 tools/generate_attributions.py [output-path]
"""

import hashlib
import json
import subprocess
import sys
from collections import defaultdict

COPYLEFT_PREFIXES = ("GPL-", "LGPL-", "AGPL-", "MPL-")

# The embedded egui fonts carry their own vendored license files, shipped in
# the licenses/ directory of every release archive.
FONT_LICENSE_FILES = {
    "OFL-1.1": "licenses/OFL-1.1.txt",
    "Ubuntu-font-1.0": "licenses/Ubuntu-Font-Licence-1.0.txt",
}

MIT_CANONICAL = """\
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE.
"""

ZLIB_CANONICAL = """\
This software is provided 'as-is', without any express or implied warranty.
In no event will the authors be held liable for any damages arising from the
use of this software.

Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it
freely, subject to the following restrictions:

1. The origin of this software must not be misrepresented; you must not
   claim that you wrote the original software. If you use this software in a
   product, an acknowledgment in the product documentation would be
   appreciated but is not required.

2. Altered source versions must be plainly marked as such, and must not be
   misrepresented as being the original software.

3. This notice may not be removed or altered from any source distribution.
"""

BSL_CANONICAL = """\
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""

CANONICAL_TEXTS = {
    "MIT": MIT_CANONICAL,
    "Zlib": ZLIB_CANONICAL,
    "BSL-1.0": BSL_CANONICAL,
}


def is_missing(text):
    return text in (None, "", "NOT FOUND")


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "THIRD-PARTY-LICENSES.md"
    # encoding is explicit: Windows would otherwise decode with the legacy
    # locale codepage, which cannot represent all bytes in license texts.
    raw = subprocess.run(
        ["cargo", "bundle-licenses", "--format", "json"],
        capture_output=True,
        encoding="utf-8",
        errors="replace",
        check=True,
    ).stdout
    libs = json.loads(raw)["third_party_libraries"]
    libs.sort(key=lambda l: (l["package_name"].lower(), l["package_version"]))

    # Distinct found texts, and missing texts grouped by license id.
    texts = {}  # sha1 -> {"text": str, "license": str, "crates": [str]}
    missing = defaultdict(list)  # license id -> [crate]
    elected_away = defaultdict(list)  # skipped copyleft option -> [crate]

    for lib in libs:
        crate = f'{lib["package_name"]} {lib["package_version"]}'
        expression = lib.get("license") or ""
        multi = " OR " in expression
        for lic in lib.get("licenses", []):
            lid = lic.get("license", "")
            if multi and lid.startswith(COPYLEFT_PREFIXES):
                elected_away[lid].append(crate)
                continue
            text = lic.get("text")
            if is_missing(text):
                missing[lid].append(crate)
            else:
                h = hashlib.sha1(text.encode()).hexdigest()
                entry = texts.setdefault(h, {"text": text, "license": lid, "crates": []})
                entry["crates"].append(crate)

    out = []
    out.append("# Third-Party Licenses\n")
    out.append(
        "This file lists every Rust crate compiled into this binary "
        "distribution of Craps-Sim, together with its license. It is "
        "generated per release platform by `tools/generate_attributions.py`. "
        "The embedded GUI fonts are attributed separately in "
        "THIRD-PARTY-NOTICES.md and the `licenses/` directory.\n"
    )
    if elected_away:
        opts = ", ".join(sorted(elected_away))
        out.append(
            f"Some crates are multi-licensed with a copyleft option ({opts}); "
            "this distribution uses those crates under their permissive "
            "option, whose text appears below.\n"
        )

    out.append("## Crate index\n")
    out.append("| Crate | Version | License |")
    out.append("| --- | --- | --- |")
    for lib in libs:
        out.append(
            f'| {lib["package_name"]} | {lib["package_version"]} | {lib.get("license") or "?"} |'
        )
    out.append("")

    out.append("## License texts\n")
    ordered = sorted(texts.values(), key=lambda e: (e["license"], e["crates"][0].lower()))
    for entry in ordered:
        crates = ", ".join(entry["crates"])
        out.append(f'### {entry["license"]} — {crates}\n')
        out.append("```text")
        out.append(entry["text"].rstrip("\n"))
        out.append("```\n")

    if missing:
        out.append("## Crates whose packages do not include a license text\n")
        out.append(
            "The following crates declare their license in metadata without "
            "packaging the text. The canonical text of each license follows; "
            "its copyright rests with the crate's authors.\n"
        )
        for lid in sorted(missing):
            crates = ", ".join(missing[lid])
            out.append(f"### {lid} — {crates}\n")
            if lid in FONT_LICENSE_FILES:
                out.append(
                    f"See `{FONT_LICENSE_FILES[lid]}` in this archive for the full text.\n"
                )
                continue
            canonical = CANONICAL_TEXTS.get(lid)
            if canonical is None and lid == "Apache-2.0":
                # Reuse the canonical Apache-2.0 text already harvested from
                # another crate (the license body is crate-independent).
                apache = [e for e in texts.values() if e["license"] == "Apache-2.0"]
                if apache:
                    canonical = max(apache, key=lambda e: len(e["crates"]))["text"]
            if canonical:
                out.append("```text")
                out.append(canonical.rstrip("\n"))
                out.append("```\n")
            else:
                out.append(
                    f"Full text: https://spdx.org/licenses/{lid}.html\n"
                )

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(
        f"wrote {out_path}: {len(libs)} crates, {len(texts)} distinct texts, "
        f"{sum(len(v) for v in missing.values())} canonical-text fallbacks"
    )


if __name__ == "__main__":
    main()
